# Generated by Django 3.0.5 on 2020-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('quality', models.IntegerField(choices=[(240, '240p'), (360, '360p'), (480, '480p'), (720, '720p'), (1080, '1080p')])),
                ('file_size', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('restricted', models.BooleanField(default=False)),
                ('imdb_url', models.URLField(blank=True, null=True)),
                ('file_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('length', models.TimeField(blank=True, null=True)),
                ('tel_message_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Waiting for download'), (2, 'Downloading'), (3, 'Download Completed'), (4, 'Waiting for upload'), (5, 'Uploading'), (6, 'Upload Completed'), (7, 'Ready for Watching'), (8, 'Invalid')], default=0)),
                ('magnet_link', models.CharField(max_length=512)),
            ],
        ),
    ]
