# Generated by Django 3.0.5 on 2020-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200530_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tel_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
