# Generated by Django 3.0.5 on 2020-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200530_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='magnet_hash',
            field=models.CharField(default='aaaaaaaaaaaaaa', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='provider',
            field=models.CharField(default='yts', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='provider_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
